"""Isolated feature stdio JSON-RPC runtime contract."""

from .client import IsolatedFeatureClient, SubprocessIsolatedFeatureClient
from .context import get_tool_execution_context
from .protocol import (
    CONFIG_TRANSITION,
    CONFIG_TRANSITION_APPLIED,
    CONFIG_TRANSITION_CAPABILITY,
    CONFIG_TRANSITION_RESTART,
    FEATURE_EVENT,
    HEALTH,
    INITIALIZE,
    JSONRPC_VERSION,
    PROTOCOL_VERSION,
    SHUTDOWN,
    TOOL_EXECUTION_CONTEXT,
    TOOL_EXECUTION_CONTEXT_CAPABILITY,
    TOOL_EXECUTION_CONTEXT_VERSION,
    TOOLS_CALL,
    TOOLS_LIST,
    ConfigTransitionCapabilities,
    ConfigTransitionError,
    ConfigTransitionResult,
    ConfigTransitionUnsupportedError,
    JsonRpcError,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    ProtocolError,
    ToolExecutionContext,
    ToolExecutionContextCapabilities,
    ToolExecutionContextUnsupportedError,
    ToolExecutionTrigger,
    ToolMetadata,
    decode_message,
    encode_message,
)
from .service import IsolatedFeatureService

__all__ = [
    "CONFIG_TRANSITION",
    "CONFIG_TRANSITION_APPLIED",
    "CONFIG_TRANSITION_CAPABILITY",
    "CONFIG_TRANSITION_RESTART",
    "FEATURE_EVENT",
    "HEALTH",
    "INITIALIZE",
    "JSONRPC_VERSION",
    "PROTOCOL_VERSION",
    "SHUTDOWN",
    "TOOL_EXECUTION_CONTEXT",
    "TOOL_EXECUTION_CONTEXT_CAPABILITY",
    "TOOL_EXECUTION_CONTEXT_VERSION",
    "TOOLS_CALL",
    "TOOLS_LIST",
    "IsolatedFeatureClient",
    "IsolatedFeatureService",
    "ConfigTransitionCapabilities",
    "ConfigTransitionError",
    "ConfigTransitionResult",
    "ConfigTransitionUnsupportedError",
    "JsonRpcError",
    "JsonRpcNotification",
    "JsonRpcRequest",
    "JsonRpcResponse",
    "ProtocolError",
    "ToolExecutionContext",
    "ToolExecutionContextCapabilities",
    "ToolExecutionContextUnsupportedError",
    "ToolExecutionTrigger",
    "SubprocessIsolatedFeatureClient",
    "ToolMetadata",
    "decode_message",
    "encode_message",
    "get_tool_execution_context",
]
