"""Kestrel SDK — Voice provider interfaces."""

from .base import TTSProvider, STTProvider, VoiceInfo, VoiceConfig, match_voice, split_sentences
from .conversation_base import (
    AudioFormat,
    ConversationCapabilities,
    ConversationEvent,
    ConversationProvider,
    ConversationSession,
    EphemeralClientSecret,
    ErrorEvent,
    RealtimeClientSession,
    RealtimeTransport,
    ResponseAudioDeltaEvent,
    ResponseDoneEvent,
    ResponseTextDeltaEvent,
    SessionCreatedEvent,
    SessionUpdatedEvent,
    SpeechStartedEvent,
    SpeechStoppedEvent,
    ToolCallBatchRequestedEvent,
    ToolCallRequestedEvent,
    ToolDef,
    TranscriptDeltaEvent,
    TranscriptFinalEvent,
    TurnDetectionConfig,
    VoiceToolCall,
    VoiceToolResult,
)

__all__ = [
    "TTSProvider",
    "STTProvider",
    "VoiceInfo",
    "VoiceConfig",
    "match_voice",
    "split_sentences",
    # Conversation (speech-to-speech) provider contract.
    "ConversationProvider",
    "ConversationSession",
    "ConversationEvent",
    "AudioFormat",
    "ConversationCapabilities",
    "RealtimeTransport",
    "EphemeralClientSecret",
    "RealtimeClientSession",
    "TurnDetectionConfig",
    "ToolDef",
    # Event types.
    "SessionCreatedEvent",
    "SessionUpdatedEvent",
    "SpeechStartedEvent",
    "SpeechStoppedEvent",
    "TranscriptDeltaEvent",
    "TranscriptFinalEvent",
    "ResponseAudioDeltaEvent",
    "ResponseTextDeltaEvent",
    "ResponseDoneEvent",
    "ToolCallRequestedEvent",
    "ToolCallBatchRequestedEvent",
    "VoiceToolCall",
    "VoiceToolResult",
    "ErrorEvent",
]
